accounts:
- terminal_erp/accounts/*
- terminal_erp/controllers/accounts_controller.py
- terminal_erp/controllers/taxes_and_totals.py

stock:
- terminal_erp/stock/*
- terminal_erp/controllers/stock_controller.py
- terminal_erp/controllers/item_variant.py

assets:
- terminal_erp/assets/*

regional:
- terminal_erp/regional/*

selling:
- terminal_erp/selling/*
- terminal_erp/controllers/selling_controller.py

buying:
- terminal_erp/buying/*
- terminal_erp/controllers/buying_controller.py

support:
- terminal_erp/support/*

POS:
- pos*

ecommerce:
- terminal_erp/e_commerce/*

maintenance:
- terminal_erp/maintenance/*

manufacturing:
- terminal_erp/manufacturing/*

crm:
- terminal_erp/crm/*

HR:
- terminal_erp/hr/*

payroll:
- terminal_erp/payroll*

projects:
- terminal_erp/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['terminal_erp/**/*.py']
  all: ['!terminal_erp/**/test*.py']
